### ISSUE TITLE
Placeholders not working in holograms

### ISSUE THREAD

**Issue by good3n** [Auxilor/EcoCrates#16]
![Crate](https://i.gyazo.com/c08e9a1f4df0b16510acaeae523bbd40.png)

```
- id: spawner
```

```yaml
hologram:
  height: 2
  ticks: 200
  frames:
    - tick: 0
      lines:
        - "<g:#9C61B8>Spawner Crate</g:#A94DB8>"
        - "&fYou have &#9C61B8%ecocrates_spawner_keys% &fkeys"
        - "&7Left-click to Preview"
        - '&7Right-click to Open'
```
