### ISSUE TITLE
Items as NBT tags dont work

### ISSUE THREAD

**Issue by AkatGabrielGoncalves** [Auxilor/EcoCrates#39]
**Describe the bug**
Simple, I cant specify Items as whole NBT tags, I tried almost every possibility. Then I just cloned the project and started experimenting and when the plugin understood my configs it just gives me {ItemStack:AIR}, which by all means is not a netherite sword.

**To Reproduce**
 - Just set an nbt tag as item reward.
 - Examples:
   ```
   - display:
      item: bedrock
      lore:
        - "&fDisplay Chance: &a%chance%%"
        - "&fActual Chance: &a%actual_chance%%"
      name: <g:#00ffff>Rare Bedrock</g:#00ff00>
    weight:
      actual: 88
      display: 0
      permission-multipliers: false
    max-wins: -1
    messages:
      - You won the rare bedrock!
    id: bedrock
    items:
      - '{id:"stone",Count:3,tag:{Name:"your name"}}'
    commands: []
    ```

**Expected behavior**
Give me an Item with the specifications of the NBT tag.

**Server Information (please complete the following information):**
- Paper-51 1.19 -> API Version 1.19-R0.1
- eco: 6.37.2
- ecocrates 1.12.1

**Additional context**
I was trying to make the creation of rewards and crates more bearable when I discovered that nbt tags dont work or I don't know how to use it even though I followed the docs. My modified version didnt work then I tried the clean version and it didnt work too.
